
use_frameworks!
platform :ios, '12.0'

target 'FSUIKit_Example' do
  pod 'FSUIKitSwift', :path => '../'
  pod 'SnapKit'
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "VincentLee"
  # disable bitcode.
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
