
use_frameworks!
platform :ios, '13.0'

target 'FSUIKit_Example' do
  pod 'FSUIKitSwift', :path => '../'
  pod 'SnapKit'
end

post_install do |installer|
  installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "VincentLee"
  installer.pods_project.targets.each do |target|
    if target.platform_name == :ios then
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['CODE_SIGN_IDENTITY'] = 'Don\'t Code Sign'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
